FROM gradle:7.6-jdk17 as development

WORKDIR /app

# Copy the Gradle configuration files
COPY build.gradle .
COPY settings.gradle .
COPY gradle.properties* ./
COPY gradlew* ./
COPY gradle ./gradle

# Copy the source code
COPY src ./src

# Remote debugging configuration
ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"

# Start the Spring Boot application with Spring Boot DevTools
CMD ["./gradlew", "bootRun", "--args='--spring.profiles.active=dev'"]
