FROM maven:3.9-eclipse-temurin-17 as development

WORKDIR /app

# Copy the Maven configuration files
COPY pom.xml .
COPY settings.gradle .

# Copy the source code
COPY src ./src

# Remote debugging configuration
ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"

# Start the Spring Boot application with Spring Boot DevTools
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-Dspring.profiles.active=dev'"]
