-- H2-compatible SQL syntax for tests
-- Test-specific schema changes and additions for V99, building upon V1.

-- Modifying tables created in V1 to match V99's intended schema.

-- Modify car_conditions from V1 definition
ALTER TABLE car_conditions ALTER COLUMN name VARCHAR(50);
ALTER TABLE car_conditions ALTER COLUMN display_name_en VARCHAR(100);
ALTER TABLE car_conditions ALTER COLUMN display_name_ar VARCHAR(100);
-- V1: name VARCHAR(255) NOT NULL. V99 wants: name VARCHAR(50) NOT NULL. (Nullability unchanged)
-- V1: display_name_en VARCHAR(255) nullable. V99 wants: display_name_en VARCHAR(100) NOT NULL.
ALTER TABLE car_conditions ALTER COLUMN display_name_en SET NOT NULL;
-- V1: display_name_ar VARCHAR(255) nullable. V99 wants: display_name_ar VARCHAR(100) NOT NULL.
ALTER TABLE car_conditions ALTER COLUMN display_name_ar SET NOT NULL;
ALTER TABLE car_conditions DROP COLUMN slug;
ALTER TABLE car_conditions DROP COLUMN created_at;
ALTER TABLE car_conditions DROP COLUMN updated_at;

-- Modify body_styles from V1 definition
ALTER TABLE body_styles ALTER COLUMN name VARCHAR(50);
ALTER TABLE body_styles ALTER COLUMN display_name_en VARCHAR(100);
ALTER TABLE body_styles ALTER COLUMN display_name_ar VARCHAR(100);
-- V1: name VARCHAR(255) NOT NULL. V99 wants: name VARCHAR(50) NOT NULL.
-- V1: display_name_en VARCHAR(255) nullable. V99 wants: display_name_en VARCHAR(100) NOT NULL.
ALTER TABLE body_styles ALTER COLUMN display_name_en SET NOT NULL;
-- V1: display_name_ar VARCHAR(255) nullable. V99 wants: display_name_ar VARCHAR(100) NOT NULL.
ALTER TABLE body_styles ALTER COLUMN display_name_ar SET NOT NULL;
ALTER TABLE body_styles DROP COLUMN slug;
ALTER TABLE body_styles DROP COLUMN created_at;
ALTER TABLE body_styles DROP COLUMN updated_at;

-- Modify transmissions from V1 definition
ALTER TABLE transmissions ALTER COLUMN name VARCHAR(50);
ALTER TABLE transmissions ALTER COLUMN display_name_en VARCHAR(100);
ALTER TABLE transmissions ALTER COLUMN display_name_ar VARCHAR(100);
-- V1: name VARCHAR(255) NOT NULL. V99 wants: name VARCHAR(50) NOT NULL.
-- V1: display_name_en VARCHAR(255) nullable. V99 wants: display_name_en VARCHAR(100) NOT NULL.
ALTER TABLE transmissions ALTER COLUMN display_name_en SET NOT NULL;
-- V1: display_name_ar VARCHAR(255) nullable. V99 wants: display_name_ar VARCHAR(100) NOT NULL.
ALTER TABLE transmissions ALTER COLUMN display_name_ar SET NOT NULL;
ALTER TABLE transmissions DROP COLUMN slug;
ALTER TABLE transmissions DROP COLUMN created_at;
ALTER TABLE transmissions DROP COLUMN updated_at;

-- Modify fuel_types from V1 definition
ALTER TABLE fuel_types ALTER COLUMN name VARCHAR(50);
ALTER TABLE fuel_types ALTER COLUMN display_name_en VARCHAR(100);
ALTER TABLE fuel_types ALTER COLUMN display_name_ar VARCHAR(100);
-- V1: name VARCHAR(255) NOT NULL. V99 wants: name VARCHAR(50) NOT NULL.
-- V1: display_name_en VARCHAR(255) nullable. V99 wants: display_name_en VARCHAR(100) NOT NULL.
ALTER TABLE fuel_types ALTER COLUMN display_name_en SET NOT NULL;
-- V1: display_name_ar VARCHAR(255) nullable. V99 wants: display_name_ar VARCHAR(100) NOT NULL.
ALTER TABLE fuel_types ALTER COLUMN display_name_ar SET NOT NULL;
ALTER TABLE fuel_types DROP COLUMN slug;
ALTER TABLE fuel_types DROP COLUMN created_at;
ALTER TABLE fuel_types DROP COLUMN updated_at;

-- Modify drive_types from V1 definition
ALTER TABLE drive_types ALTER COLUMN name VARCHAR(50);
ALTER TABLE drive_types ALTER COLUMN display_name_en VARCHAR(100);
ALTER TABLE drive_types ALTER COLUMN display_name_ar VARCHAR(100);
-- V1: name VARCHAR(255) NOT NULL. V99 wants: name VARCHAR(50) NOT NULL.
-- V1: display_name_en VARCHAR(255) nullable. V99 wants: display_name_en VARCHAR(100) NOT NULL.
ALTER TABLE drive_types ALTER COLUMN display_name_en SET NOT NULL;
-- V1: display_name_ar VARCHAR(255) nullable. V99 wants: display_name_ar VARCHAR(100) NOT NULL.
ALTER TABLE drive_types ALTER COLUMN display_name_ar SET NOT NULL;
ALTER TABLE drive_types DROP COLUMN slug;
ALTER TABLE drive_types DROP COLUMN created_at;
ALTER TABLE drive_types DROP COLUMN updated_at;

-- Modify car_listings from V1 definition
-- V1: updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- V99 wants: updated_at TIMESTAMP NOT NULL (no default)
ALTER TABLE car_listings ALTER COLUMN updated_at DROP DEFAULT;
ALTER TABLE car_listings ALTER COLUMN updated_at SET NOT NULL; -- Ensure NOT NULL if V1 was different, though both are NOT NULL.

-- Tables like users, roles, user_roles, locations, listing_media, ad_packages,
-- ad_services, listing_packages, listing_services, user_activity_logs are assumed
-- to be identical to V1 definitions or V1 is authoritative, so no CREATE/ALTER here.

-- Create new tables specific to V99

CREATE TABLE seller_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    display_name_en VARCHAR(100) NOT NULL,
    display_name_ar VARCHAR(100) NOT NULL
);

-- Default roles are inserted in V1, so no need to repeat here.
-- Favorites table is now defined consistently in V1, so no need to repeat here.

-- H2 doesn't support PostgreSQL-style triggers
-- For testing purposes, we'll rely on the TestDataGenerator to set the updated_at field explicitly
-- (This comment was in V99 and can remain if relevant to its logic, though updated_at handling is now via ALTER)
