-- Migration R: reference_data
-- Created: 2025-05-22
-- Updated: 2025-09-13 - Using PostgreSQL 14 compatible INSERT ... ON CONFLICT syntax

-- Car Conditions
INSERT INTO car_conditions (name, display_name_en, display_name_ar, slug)
VALUES
    ('new', 'New', 'جديد', 'new'),
    ('like_new', 'Like New', 'شبه جديد', 'like-new'),
    ('excellent', 'Excellent', 'ممتاز', 'excellent'),
    ('very_good', 'Very Good', 'جيد جداً', 'very-good'),
    ('good', 'Good', 'جيد', 'good'),
    ('fair', 'Fair', 'مقبول', 'fair'),
    ('salvage', 'Salvage', 'للقطع', 'salvage')
ON CONFLICT (name) DO UPDATE SET
    display_name_en = EXCLUDED.display_name_en,
    display_name_ar = EXCLUDED.display_name_ar,
    slug = EXCLUDED.slug;

-- Drive Types
INSERT INTO drive_types (name, display_name_en, display_name_ar, slug)
VALUES
    ('fwd', 'Front-Wheel Drive', 'دفع أمامي', 'fwd'),
    ('rwd', 'Rear-Wheel Drive', 'دفع خلفي', 'rwd'),
    ('awd', 'All-Wheel Drive', 'دفع رباعي', 'awd'),
    ('4wd', 'Four-Wheel Drive', 'دفع رباعي', '4wd')
ON CONFLICT (name) DO UPDATE SET
    display_name_en = EXCLUDED.display_name_en,
    display_name_ar = EXCLUDED.display_name_ar,
    slug = EXCLUDED.slug;

-- Body Styles
INSERT INTO body_styles (name, display_name_en, display_name_ar, slug)
VALUES
    ('sedan', 'Sedan', 'سيدان', 'sedan'),
    ('suv', 'SUV', 'إس يو في', 'suv'),
    ('hatchback', 'Hatchback', 'هاتشباك', 'hatchback'),
    ('coupe', 'Coupe', 'كوبيه', 'coupe'),
    ('pickup', 'Pickup Truck', 'بيك أب', 'pickup'),
    ('convertible', 'Convertible', 'مكشوفة', 'convertible'),
    ('wagon', 'Wagon', 'ستيشن', 'wagon'),
    ('van', 'Van', 'فان', 'van'),
    ('minivan', 'Minivan', 'ميني فان', 'minivan'),
    ('crossover', 'Crossover', 'كروس أوفر', 'crossover')
ON CONFLICT (name) DO UPDATE SET
    display_name_en = EXCLUDED.display_name_en,
    display_name_ar = EXCLUDED.display_name_ar,
    slug = EXCLUDED.slug;

-- Fuel Types
INSERT INTO fuel_types (name, display_name_en, display_name_ar, slug)
VALUES
    ('gasoline', 'Gasoline', 'بنزين', 'gasoline'),
    ('diesel', 'Diesel', 'ديزل', 'diesel'),
    ('hybrid', 'Hybrid', 'هجين', 'hybrid'),
    ('electric', 'Electric', 'كهرباء', 'electric'),
    ('cng', 'CNG', 'غاز طبيعي', 'cng'),
    ('lpg', 'LPG', 'غاز مسال', 'lpg')
ON CONFLICT (name) DO UPDATE SET
    display_name_en = EXCLUDED.display_name_en,
    display_name_ar = EXCLUDED.display_name_ar,
    slug = EXCLUDED.slug;

-- Transmissions
INSERT INTO transmissions (name, display_name_en, display_name_ar, slug)
VALUES
    ('automatic', 'Automatic', 'أوتوماتيك', 'automatic'),
    ('manual', 'Manual', 'عادي', 'manual'),
    ('cvt', 'CVT', 'تعشيق مستمر', 'cvt'),
    ('semi_auto', 'Semi-Automatic', 'نصف أوتوماتيك', 'semi-auto'),
    ('dual_clutch', 'Dual Clutch', 'ثنائي القابض', 'dual-clutch')
ON CONFLICT (name) DO UPDATE SET
    display_name_en = EXCLUDED.display_name_en,
    display_name_ar = EXCLUDED.display_name_ar,
    slug = EXCLUDED.slug;

-- Seller Types
CREATE TABLE IF NOT EXISTS seller_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) UNIQUE NOT NULL,
    display_name_en VARCHAR(50) NOT NULL,
    display_name_ar VARCHAR(50) NOT NULL,
    slug VARCHAR(50) NOT NULL
);

INSERT INTO seller_types (name, display_name_en, display_name_ar, slug)
VALUES
    ('private', 'Private Seller', 'بائع خاص', 'private'),
    ('dealer', 'Dealer', 'معرض سيارات', 'dealer'),
    ('certified', 'Certified Dealer', 'معرض معتمد', 'certified')
ON CONFLICT (name) DO UPDATE SET
    display_name_en = EXCLUDED.display_name_en,
    display_name_ar = EXCLUDED.display_name_ar,
    slug = EXCLUDED.slug;
