CREATE TABLE sync_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    last_sync_time TIMESTAMP,
    last_sync_message TEXT,
    total_records_synced BIGINT,
    total_records_failed BIGINT,
    start_time TIMESTAMP,
    CONSTRAINT uk_sync_status_provider_name UNIQUE (provider_name)
);
