-- Migration V54: Create user reports table
-- This migration adds the user reporting functionality to allow users to report abusive, inappropriate, or suspicious behavior

-- USER_REPORTS TABLE
CREATE TABLE user_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reported_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    conversation_id BIGINT REFERENCES conversations(id) ON DELETE SET NULL,
    report_type VARCHAR(50) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED')),
    admin_notes VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    resolved_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL,

    -- Prevent self-reporting
    CONSTRAINT ck_reporter_not_reported CHECK (reporter_id != reported_user_id)
);

-- Indexes for better query performance
CREATE INDEX idx_user_reports_reporter ON user_reports(reporter_id);
CREATE INDEX idx_user_reports_reported_user ON user_reports(reported_user_id);
CREATE INDEX idx_user_reports_status ON user_reports(status);
CREATE INDEX idx_user_reports_conversation ON user_reports(conversation_id);
CREATE INDEX idx_user_reports_created_at ON user_reports(created_at DESC);

-- Composite index for admin queries (status + creation date)
CREATE INDEX idx_user_reports_status_created ON user_reports(status, created_at DESC);

-- Unique constraint to prevent duplicate pending reports
-- (PostgreSQL partial unique index - only enforced when status = 'PENDING')
CREATE UNIQUE INDEX idx_unique_pending_report 
ON user_reports(reporter_id, reported_user_id) 
WHERE status = 'PENDING';

-- Comments for documentation
COMMENT ON TABLE user_reports IS 'Stores user reports for abusive, inappropriate, or suspicious behavior';
COMMENT ON COLUMN user_reports.reporter_id IS 'The user who submitted the report';
COMMENT ON COLUMN user_reports.reported_user_id IS 'The user being reported';
COMMENT ON COLUMN user_reports.conversation_id IS 'Optional reference to conversation context if report is conversation-related';
COMMENT ON COLUMN user_reports.report_type IS 'Type of report (e.g., SPAM, HARASSMENT, SCAM, INAPPROPRIATE_CONTENT, OTHER)';
COMMENT ON COLUMN user_reports.status IS 'Status of the report: PENDING, REVIEWED, RESOLVED, DISMISSED';

