-- Migration V55: Create user blocks table for user-level blocking
-- This allows users to block other users completely across the entire platform

CREATE TABLE user_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Prevent blocking yourself
    CONSTRAINT ck_blocker_not_blocked CHECK (blocker_id != blocked_id),
    
    -- Prevent duplicate blocks
    CONSTRAINT uk_blocker_blocked UNIQUE(blocker_id, blocked_id)
);

-- Indexes for performance
CREATE INDEX idx_user_blocks_blocker ON user_blocks(blocker_id);
CREATE INDEX idx_user_blocks_blocked ON user_blocks(blocked_id);
CREATE INDEX idx_user_blocks_created_at ON user_blocks(created_at DESC);

-- Comments for documentation
COMMENT ON TABLE user_blocks IS 'Stores user-level blocks - prevents all interactions between users';
COMMENT ON COLUMN user_blocks.blocker_id IS 'The user who initiated the block';
COMMENT ON COLUMN user_blocks.blocked_id IS 'The user who is blocked';

