-- Create the new countries table
CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code VARCHAR(2) NOT NULL UNIQUE,
    display_name_en VARCHAR(255) NOT NULL,
    display_name_ar VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert Syria as the default country
INSERT INTO countries (country_code, display_name_en, display_name_ar, is_active)
VALUES ('SY', 'Syria', 'سوريا', TRUE);

-- Alter governorates table
ALTER TABLE governorates
ADD COLUMN country_id BIGINT;

-- Add the foreign key constraint first
ALTER TABLE governorates
ADD CONSTRAINT fk_governorates_country
    FOREIGN KEY (country_id)
    REFERENCES countries(id);

-- Update ALL existing governorates to link to the Syrian country
-- This assumes all existing governorates should now belong to Syria.
UPDATE governorates
SET country_id = (SELECT c.id FROM countries c WHERE c.country_code = 'SY');

-- Now that all governorates should have a country_id, make the column NOT NULL.
ALTER TABLE governorates
ALTER COLUMN country_id SET NOT NULL;

-- Drop the old country_code column from governorates
ALTER TABLE governorates
DROP COLUMN country_code;

-- Alter locations table - Add column first
ALTER TABLE locations
ADD COLUMN governorate_id BIGINT;

-- Add foreign key constraint separately
ALTER TABLE locations
ADD CONSTRAINT fk_locations_governorate
    FOREIGN KEY (governorate_id)
    REFERENCES governorates(id);

-- Note: Populating locations.governorate_id is complex and depends on existing data relationships.
-- This script does not automatically populate locations.governorate_id.
-- This will require a separate data migration effort based on specific business rules
-- or manual updates if the dataset is small.
-- For new listings, the application logic will ensure governorate_id is set.

-- Drop the old country_code column from locations
-- This is safe only if locations are always accessed via governorate -> country
-- or if the application logic is updated to no longer rely on locations.country_code directly.
-- Given the new hierarchy, this should be the case.
ALTER TABLE locations
DROP COLUMN country_code;


-- Update existing rows to have a default value for created_at and updated_at if they are NULL
-- Note: created_at and updated_at columns already exist from V1 migration
UPDATE governorates SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE governorates SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;
UPDATE locations SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE locations SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;

