package com.autotrader.autotraderbackend.payload.response;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor // Creates constructor with all fields
public class MessageResponse {
    private String message;

    // Constructor, getter, and setter are generated by Lombok
}
